build:
	sudo cp setup /usr/local/bin/setup
	sudo chmod +x /usr/local/bin/setup
	sudo cp list_disk /usr/local/bin/list_disk
	sudo chmod +x /usr/local/bin/list_disk
	sudo cp inled-archive.key /usr/local/bin/inled-archive.key
	cd frontend && npm start
clean:
	exit
